import type { AiProviderAdapter, AiProviderAdapterResult } from './types.js';

const isRecord = (value: unknown): value is Record<string, unknown> => {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
};

const getNestedRecord = (value: unknown, key: string): Record<string, unknown> | null => {
  if (!isRecord(value)) {
    return null;
  }

// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  const nested = value[key];
  return isRecord(nested) ? nested : null;
};

const getBooleanFlag = (input: Record<string, unknown>, key: string): boolean => {
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  if (input[key] === true) {
    return true;
  }

  const attributes = getNestedRecord(input, 'attributes');
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  return attributes?.[key] === true;
};

const getStringValue = (input: Record<string, unknown>, key: string): string | null => {
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  if (typeof input[key] === 'string' && input[key].trim().length > 0) {
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
    return input[key].trim();
  }

  const attributes = getNestedRecord(input, 'attributes');
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  if (typeof attributes?.[key] === 'string' && attributes[key].trim().length > 0) {
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
    return attributes[key].trim();
  }

  return null;
};

const getRecordValue = (input: Record<string, unknown>, key: string): Record<string, unknown> | null => {
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  if (isRecord(input[key])) {
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
    return input[key];
  }

  const attributes = getNestedRecord(input, 'attributes');
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
// eslint-disable-next-line security/detect-object-injection -- 从内部枚举构造的键
  return isRecord(attributes?.[key]) ? (attributes[key]) : null;
};

const buildDefaultAgentDecision = (input: {
  actorDisplayName: string;
  worldName: string;
  mockActionType?: string | null;
  mockContent?: string | null;
  semanticTargetRef?: Record<string, unknown> | null;
  semanticIntentKind?: string | null;
  semanticIntentText?: string | null;
  semanticIntentDesiredEffect?: string | null;
  semanticIntentProposedMethod?: string | null;
}): Record<string, unknown> => {
  if (input.mockActionType === 'semantic_intent') {
    return {
      action_type: 'semantic_intent',
      target_ref: input.semanticTargetRef ?? null,
      payload: {
        semantic_intent_kind: input.semanticIntentKind ?? 'ritual_divination',
        ...(input.semanticIntentDesiredEffect ? { semantic_intent_desired_effect: input.semanticIntentDesiredEffect } : {}),
        ...(input.semanticIntentProposedMethod ? { semantic_intent_proposed_method: input.semanticIntentProposedMethod } : {})
      },
      confidence: 0.88,
      delay_hint_ticks: '1',
      reasoning: input.semanticIntentText ?? 'The actor attempts an unsupported semantic action.',
      meta: {
        provider_mode: 'mock_gateway_semantic_intent'
      }
    };
  }

  return {
    action_type: input.mockActionType ?? 'post_message',
    target_ref: null,
    payload: {
      content: input.mockContent ?? `Mock AI gateway decision from ${input.actorDisplayName} in ${input.worldName}.`
    },
    confidence: 0.99,
    delay_hint_ticks: '1',
    reasoning: 'Generated by the mock AI provider adapter.',
    meta: {
      provider_mode: 'mock_gateway'
    }
  };
};

const buildCompletedResult = (output: AiProviderAdapterResult['output']): AiProviderAdapterResult => {
  return {
    status: 'completed',
    finish_reason: 'stop',
    output,
    usage: {
      input_tokens: 64,
      output_tokens: 32,
      total_tokens: 96,
      estimated_cost_usd: 0,
      latency_ms: 5
    },
    safety: {
      blocked: false,
      reason_code: null,
      provider_signal: null
    },
    raw_ref: {
      provider_request_id: 'mock-request',
      provider_response_id: 'mock-response'
    },
    error: null
  };
};

export const createMockAiProviderAdapter = (): AiProviderAdapter => {
  return {
    provider: 'mock',
    execute(input) {
      const taskInput = input.task_request.input;

      if (getBooleanFlag(taskInput, 'force_provider_fail') || getBooleanFlag(taskInput, 'force_fail')) {
        return Promise.resolve({
          status: 'failed',
          finish_reason: 'error',
          output: {
            mode: input.request.response_mode
          },
          usage: {
            latency_ms: 3
          },
          safety: {
            blocked: false,
            reason_code: null,
            provider_signal: null
          },
          raw_ref: {
            provider_request_id: 'mock-request',
            provider_response_id: null
          },
          error: {
            code: 'AI_PROVIDER_FAIL',
            message: 'Forced mock AI provider failure',
            retryable: true,
            stage: 'provider'
          }
        });
      }

      if (input.request.response_mode === 'embedding') {
        return Promise.resolve(buildCompletedResult({
          mode: 'embedding',
          embedding: [0.12, 0.34, 0.56, 0.78]
        }));
      }

      if (input.request.response_mode === 'free_text') {
        return Promise.resolve(buildCompletedResult({
          mode: 'free_text',
          text: getStringValue(taskInput, 'mock_text') ?? 'Mock AI provider text output.'
        }));
      }

      if (isRecord(taskInput.mock_json)) {
        return Promise.resolve(buildCompletedResult({
          mode: input.request.response_mode,
          json: taskInput.mock_json
        }));
      }

      const actorDisplayName =
        getStringValue(taskInput, 'actor_display_name')
        ?? (typeof input.task_request.actor_ref?.actor_display_name === 'string'
          ? input.task_request.actor_ref.actor_display_name
          : 'Unknown Actor');
      const worldName = getStringValue(taskInput, 'world_name') ?? 'Unknown World';
      const decision = buildDefaultAgentDecision({
        actorDisplayName,
        worldName,
        mockActionType: getStringValue(taskInput, 'mock_action_type'),
        mockContent: getStringValue(taskInput, 'mock_content'),
        semanticTargetRef: getRecordValue(taskInput, 'semantic_target_ref'),
        semanticIntentKind: getStringValue(taskInput, 'semantic_intent_kind'),
        semanticIntentText: getStringValue(taskInput, 'semantic_intent_text'),
        semanticIntentDesiredEffect: getStringValue(taskInput, 'semantic_intent_desired_effect'),
        semanticIntentProposedMethod: getStringValue(taskInput, 'semantic_intent_proposed_method')
      });

      return Promise.resolve(buildCompletedResult({
        mode: input.request.response_mode,
        json: decision
      }));
    }
  };
};
