import type { InferenceProvider } from '../provider.js';

const normalizeTransmissionDelayTicks = (value: unknown): string => {
  if (typeof value === 'string' && /^\d+$/.test(value.trim())) {
    return value.trim();
  }

  if (typeof value === 'number' && Number.isSafeInteger(value) && value >= 0) {
    return String(value);
  }

  return '1';
};

const normalizeTransmissionDropChance = (value: unknown): number => {
  if (typeof value === 'number' && Number.isFinite(value) && value >= 0 && value <= 1) {
    return value;
  }

  return 0;
};

const normalizeTransmissionPolicy = (value: unknown): 'reliable' | 'best_effort' | 'fragile' | 'blocked' => {
  if (
    value === 'reliable' ||
    value === 'best_effort' ||
    value === 'fragile' ||
    value === 'blocked'
  ) {
    return value;
  }

  return 'reliable';
};

const resolveTransmissionDropChanceByPolicy = (
  policy: 'reliable' | 'best_effort' | 'fragile' | 'blocked',
  explicitChance: number,
  fallbackChance: number
): number => {
  if (policy === 'blocked') {
    return 1;
  }

  if (explicitChance > 0) {
    return explicitChance;
  }

  if (fallbackChance > 0) {
    return fallbackChance;
  }

  switch (policy) {
    case 'reliable':
      return 0;
    case 'best_effort':
      return 0.15;
    case 'fragile':
      return 0.5;
    default:
      return 0;
  }
};

export const createMockInferenceProvider = (): InferenceProvider => {
  return {
    name: 'mock',
    strategies: ['mock'],
    async run(context) {
      if (context.attributes.force_fail === true) {
        throw new Error('Forced mock provider failure');
      }

      if (context.attributes.force_invalid_payload === true) {
        return {
          action_type: 'post_message',
          target_ref: null,
          payload: null
        };
      }

      if (context.attributes.mock_action_type === 'trigger_event') {
        return {
          action_type: 'trigger_event',
          target_ref: null,
          payload: {
            event_type:
              typeof context.attributes.event_type === 'string' ? context.attributes.event_type : 'interaction',
            title:
              typeof context.attributes.event_title === 'string' && context.attributes.event_title.trim().length > 0
                ? context.attributes.event_title.trim()
                : 'Mock triggered event',
            description:
              typeof context.attributes.event_description === 'string' && context.attributes.event_description.trim().length > 0
                ? context.attributes.event_description.trim()
                : 'Mock provider emitted a trigger_event action.',
            impact_data:
              context.attributes.event_impact_data && typeof context.attributes.event_impact_data === 'object' && !Array.isArray(context.attributes.event_impact_data)
                ? context.attributes.event_impact_data
                : undefined
          },
          confidence: 0.91,
          delay_hint_ticks: '1',
          reasoning: 'Generated by the mock inference provider for trigger_event.',
          meta: {
            provider_mode: 'mock_trigger_event'
          }
        };
      }

      if (context.attributes.mock_action_type === 'adjust_relationship') {
        return {
          action_type: 'adjust_relationship',
          target_ref: {
            agent_id:
              typeof context.attributes.target_agent_id === 'string' && context.attributes.target_agent_id.trim().length > 0
                ? context.attributes.target_agent_id.trim()
                : 'agent-002'
          },
          payload: {
            relationship_type:
              typeof context.attributes.relationship_type === 'string' ? context.attributes.relationship_type : 'friend',
            operation: typeof context.attributes.relationship_operation === 'string' ? context.attributes.relationship_operation : 'set',
            target_weight:
              typeof context.attributes.relationship_weight === 'number'
                ? context.attributes.relationship_weight
                : 0.5,
            create_if_missing: context.attributes.create_if_missing === true,
            reason: typeof context.attributes.relationship_reason === 'string' ? context.attributes.relationship_reason : 'mock_adjust_relationship'
          },
          confidence: 0.93,
          delay_hint_ticks: '1',
          reasoning: 'Generated by the mock inference provider for adjust_relationship.',
          meta: {
            provider_mode: 'mock_adjust_relationship'
          }
        };
      }

      if (context.attributes.mock_action_type === 'adjust_snr') {
        return {
          action_type: 'adjust_snr',
          target_ref: {
            agent_id:
              typeof context.attributes.target_agent_id === 'string' && context.attributes.target_agent_id.trim().length > 0
                ? context.attributes.target_agent_id.trim()
                : context.resolved_agent_id ?? 'agent-001'
          },
          payload: {
            operation: typeof context.attributes.snr_operation === 'string' ? context.attributes.snr_operation : 'set',
            target_snr:
              typeof context.attributes.target_snr === 'number'
                ? context.attributes.target_snr
                : typeof context.attributes.snr_target_value === 'number'
                  ? context.attributes.snr_target_value
                  : 0.5,
            reason:
              typeof context.attributes.snr_reason === 'string'
                ? context.attributes.snr_reason
                : 'mock_adjust_snr'
          },
          confidence: 0.94,
          delay_hint_ticks: '1',
          reasoning: 'Generated by the mock inference provider for adjust_snr.',
          meta: {
            provider_mode: 'mock_adjust_snr'
          }
        };
      }

      const mockedContent =
        typeof context.attributes.mock_content === 'string' && context.attributes.mock_content.trim().length > 0
          ? context.attributes.mock_content.trim()
          : `Mock decision from ${context.actor_display_name} in ${context.world_pack.name}.`;
      const transmissionPolicy = normalizeTransmissionPolicy(
        context.attributes.transmission_policy ?? context.transmission_profile.policy
      );
      const explicitDropChance = normalizeTransmissionDropChance(context.attributes.transmission_drop_chance);
      const transmissionDropChance = resolveTransmissionDropChanceByPolicy(
        transmissionPolicy,
        explicitDropChance,
        context.transmission_profile.drop_chance
      );

      return {
        action_type: 'post_message',
        target_ref: null,
        payload: {
          content: mockedContent
        },
        confidence: 0.99,
        delay_hint_ticks: '1',
        reasoning: 'Generated by the mock inference provider.',
        meta: {
          provider_mode: 'mock',
          actor_role: context.actor_ref.role,
          transmission_delay_ticks: normalizeTransmissionDelayTicks(
            context.attributes.transmission_delay_ticks ?? context.transmission_profile.delay_ticks
          ),
          transmission_policy: transmissionPolicy,
          transmission_drop_chance: transmissionDropChance,
          drop_reason: transmissionPolicy === 'blocked' ? 'policy_blocked' : context.transmission_profile.drop_reason
        }
      };
    }
  };
};
