// Re-exported from domains/ — all existing imports continue to work.
export {
  type AppConfig,
  AppConfigSchema,
  type ClockConfig,
  ClockConfigSchema,
  type FeaturesConfig,
  FeaturesConfigSchema,
  type LoggingConfig,
  LoggingConfigSchema,
  type OperatorConfig,
  OperatorConfigSchema,
  type PathsConfig,
  PathsConfigSchema,
  type PluginsConfig,
  PluginsConfigSchema,
  type PromptWorkflowConfig,
  PromptWorkflowConfigSchema,
  type RuntimeConfig,
  type RuntimeConfig_Domain,
  RuntimeConfigSchema,
  type SchedulerConfig,
  SchedulerConfigSchema,
  type SqliteConfig,
  SqliteConfigSchema,
  type StartupConfig,
  StartupConfigSchema,
  type WorldConfig,
  WorldConfigSchema,
  type WorldEngineConfig,
  WorldEngineConfigSchema} from './domains/index.js';
