import type { AppInfrastructure } from '../app/context.js';
import type { InferenceActorRef } from '../inference/types.js';
import type { MemoryEntry } from './types.js';

export interface BuildShortTermMemoryInput {
  actor_ref: InferenceActorRef;
  resolved_agent_id: string | null;
  limit?: number;
}

const DEFAULT_LIMIT = 10;

const buildTraceMemoryEntry = (trace: {
  id: string;
  strategy: string;
  provider: string;
  decision: unknown;
  created_at: bigint;
  updated_at: bigint;
}): MemoryEntry => {
  return {
    id: `mem-trace-${trace.id}`,
    scope: 'short_term',
    source_kind: 'trace',
    source_ref: { trace_id: trace.id },
    content: {
      text: `Recent decision generated by ${trace.provider} (${trace.strategy}).`,
      structured: {
        decision: trace.decision
      }
    },
    tags: ['trace', `strategy:${trace.strategy}`, `provider:${trace.provider}`],
    importance: 0.7,
    salience: 0.7,
    created_at: trace.created_at.toString(),
    occurred_at: trace.updated_at.toString(),
    visibility: {
      policy_gate: 'allow'
    },
    metadata: {
      trace_id: trace.id
    }
  };
};

const buildJobMemoryEntry = (job: {
  id: string;
  status: string;
  job_type: string;
  last_error: string | null;
  last_error_stage?: string | null;
  created_at: bigint;
  updated_at: bigint;
}): MemoryEntry => {
  return {
    id: `mem-job-${job.id}`,
    scope: 'short_term',
    source_kind: 'job',
    source_ref: { job_id: job.id },
    content: {
      text:
        job.last_error && job.last_error.length > 0
          ? `Recent job ${job.job_type} ended as ${job.status}: ${job.last_error}`
          : `Recent job ${job.job_type} is ${job.status}.`
    },
    tags: ['job', `job_type:${job.job_type}`, `job_status:${job.status}`, ...(job.last_error_stage ? [`failure:${job.last_error_stage}`] : [])],
    importance: job.status === 'failed' ? 0.9 : 0.6,
    salience: job.status === 'failed' ? 0.95 : 0.55,
    created_at: job.created_at.toString(),
    occurred_at: job.updated_at.toString(),
    visibility: {
      policy_gate: 'allow'
    },
    metadata: {
      job_id: job.id,
      last_error: job.last_error,
      last_error_stage: job.last_error_stage
    }
  };
};

const buildIntentMemoryEntry = (intent: {
  id: string;
  intent_type: string;
  status: string;
  drop_reason: string | null;
  dispatch_error_message?: string | null;
  created_at: bigint;
  updated_at: bigint;
}): MemoryEntry => {
  const reason = intent.status === 'failed' ? intent.dispatch_error_message : intent.drop_reason;
  return {
    id: `mem-intent-${intent.id}`,
    scope: 'short_term',
    source_kind: 'intent',
    source_ref: { intent_id: intent.id },
    content: {
      text:
        reason && reason.length > 0
          ? `Recent intent ${intent.intent_type} is ${intent.status}: ${reason}`
          : `Recent intent ${intent.intent_type} is ${intent.status}.`
    },
    tags: ['intent', `intent:${intent.intent_type}`, `dispatch:${intent.status}`],
    importance: intent.status === 'failed' || intent.status === 'dropped' ? 0.85 : 0.6,
    salience: intent.status === 'failed' || intent.status === 'dropped' ? 0.9 : 0.55,
    created_at: intent.created_at.toString(),
    occurred_at: intent.updated_at.toString(),
    visibility: {
      policy_gate: 'allow'
    },
    metadata: {
      intent_id: intent.id,
      status: intent.status
    }
  };
};

const buildPostMemoryEntry = (post: {
  id: string;
  author_id: string;
  content: string;
  created_at: bigint;
}): MemoryEntry => {
  return {
    id: `mem-post-${post.id}`,
    scope: 'short_term',
    source_kind: 'post',
    source_ref: { post_id: post.id },
    content: {
      text: `Recent social post by ${post.author_id}: ${post.content}`
    },
    tags: ['post', 'social', 'materialized'],
    importance: 0.5,
    salience: 0.6,
    created_at: post.created_at.toString(),
    occurred_at: post.created_at.toString(),
    visibility: {
      policy_gate: 'allow'
    },
    metadata: {
      post_id: post.id
    }
  };
};

const buildEventMemoryEntry = (event: {
  id: string;
  title: string;
  description: string;
  tick: bigint;
  type: string;
}): MemoryEntry => {
  return {
    id: `mem-event-${event.id}`,
    scope: 'short_term',
    source_kind: 'event',
    source_ref: { event_id: event.id },
    content: {
      text: `Recent event (${event.type}): ${event.title} - ${event.description}`
    },
    tags: ['event', 'narrative', `event_type:${event.type}`],
    importance: 0.55,
    salience: 0.5,
    created_at: event.tick.toString(),
    occurred_at: event.tick.toString(),
    visibility: {
      policy_gate: 'allow'
    },
    metadata: {
      event_id: event.id
    }
  };
};

const matchesActorRef = (storedActorRef: unknown, actorRef: InferenceActorRef): boolean => {
  if (!storedActorRef || typeof storedActorRef !== 'object' || Array.isArray(storedActorRef)) {
    return false;
  }

  const record = storedActorRef as Record<string, unknown>;
  return (
    record.identity_id === actorRef.identity_id ||
    (typeof record.agent_id === 'string' && record.agent_id === actorRef.agent_id)
  );
};

const filterTraceForActor = <T extends { actor_ref: unknown }>(
  entries: T[],
  actorRef: InferenceActorRef,
  limit: number
): T[] => {
  return entries.filter(entry => matchesActorRef(entry.actor_ref, actorRef)).slice(0, limit);
};

const filterJobForActor = <T extends { source_inference: { actor_ref: unknown } | null; action_intent: { actor_ref: unknown } | null }>(
  entries: T[],
  actorRef: InferenceActorRef,
  limit: number
): T[] => {
  return entries
    .filter(entry => {
      return matchesActorRef(entry.source_inference?.actor_ref, actorRef) || matchesActorRef(entry.action_intent?.actor_ref, actorRef);
    })
    .slice(0, limit);
};

export const buildShortTermMemory = async (
  context: AppInfrastructure,
  input: BuildShortTermMemoryInput
): Promise<MemoryEntry[]> => {
  const limit = input.limit ?? DEFAULT_LIMIT;

  const [traces, jobs, intents, posts, events] = await Promise.all([
    context.prisma.inferenceTrace.findMany({
      orderBy: { updated_at: 'desc' },
      take: limit * 3
    }),
    context.prisma.decisionJob.findMany({
      include: {
        source_inference: {
          select: {
            actor_ref: true
          }
        },
        action_intent: {
          select: {
            actor_ref: true
          }
        }
      },
      orderBy: { updated_at: 'desc' },
      take: limit * 3
    }),
    context.prisma.actionIntent.findMany({
      orderBy: { updated_at: 'desc' },
      take: limit * 3
    }),
    input.resolved_agent_id
      ? context.prisma.post.findMany({
          where: { author_id: input.resolved_agent_id },
          orderBy: { created_at: 'desc' },
          take: limit
        })
      : Promise.resolve([]),
    context.prisma.event.findMany({
      orderBy: { tick: 'desc' },
      take: Math.max(3, Math.ceil(limit / 2))
    })
  ]);

  return [
    ...filterTraceForActor(traces, input.actor_ref, limit).map(buildTraceMemoryEntry),
    ...filterJobForActor(jobs, input.actor_ref, limit).map(job => buildJobMemoryEntry(job)),
    ...filterTraceForActor(intents, input.actor_ref, limit).map(intent => buildIntentMemoryEntry(intent)),
    ...posts.map(buildPostMemoryEntry),
    ...events.map(buildEventMemoryEntry)
  ];
};
